import { inject, isRef } from 'vue'
import { toast as sonnerToast } from 'vue-sonner'

export type ToastVariant = 'default' | 'success' | 'info' | 'warning' | 'error'

export interface ToastMessage {
  id: string
  title?: string
  description: string
  variant: ToastVariant
  duration: number
  open: boolean
}

let toastId = 0

function resolveContainer(containerAny: any) {
  if (!containerAny) return null
  if (isRef(containerAny)) return containerAny.value ?? null
  return containerAny
}

// Use vue-sonner's `toast` if available (generated by shadcn-vue CLI), otherwise fallback to local container
const shadcnToast = typeof sonnerToast !== 'undefined' ? sonnerToast : null

export function useToast() {
  const containerAny = inject<any>('toastContainer', null)

  const showToast = (
    message: string,
    variant: ToastVariant = 'default',
    title?: string,
    duration: number = 3000
  ) => {
    // If vue-sonner is available, use its API first (preferred)
    if (shadcnToast) {
      const s: any = shadcnToast
      try {
        if (variant === 'success' && typeof s.success === 'function') {
          s.success(message, { title, duration })
          return
        }
        if (variant === 'error' && typeof s.error === 'function') {
          s.error(message, { title, duration })
          return
        }
        if (variant === 'info' && typeof s.info === 'function') {
          s.info(message, { title, duration })
          return
        }
        if (variant === 'warning' && typeof s.warning === 'function') {
          s.warning(message, { title, duration })
          return
        }
        // fallback to generic call
        if (typeof s === 'function') {
          s(message, { title, duration })
          return
        }
        if (typeof s.show === 'function') {
          s.show({ title, description: message, variant, duration })
          return
        }
      } catch (e) {
        // ignore and fallback to container below
      }
    }

    const container = resolveContainer(containerAny)
    if (!container || typeof container.addToast !== 'function') {
      // eslint-disable-next-line no-console
      console.warn('[useToast] toast container not available. message:', message)
      return
    }

    const id = `toast-${++toastId}-${Date.now()}`
    const toast: ToastMessage = {
      id,
      title,
      description: message,
      variant,
      duration,
      open: true,
    }

    container.addToast(toast)
  }

  const success = (message: string, title: string = '✓ Success') =>
    showToast(message, 'success', title, 3000)

  const error = (message: string, title: string = '✕ Error') =>
    showToast(message, 'error', title, 4000)

  const warning = (message: string, title: string = '⚠ Warning') =>
    showToast(message, 'warning', title, 3000)

  const info = (message: string, title: string = 'ℹ Info') =>
    showToast(message, 'info', title, 3000)

  const messageFn = (msg: string) => showToast(msg, 'default', undefined, 3000)

  const promise = async <T,>(
    promise: Promise<T>,
    messages: {
      loading: string
      success: string
      error: string
    }
  ): Promise<T> => {
    showToast(messages.loading, 'default', 'Loading...', 0)

    try {
      const result = await promise
      showToast(messages.success, 'success', '✓ Success', 3000)
      return result
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err)
      showToast(errorMsg || messages.error, 'error', '✕ Error', 4000)
      throw err
    }
  }

  return {
    success,
    error,
    warning,
    info,
    message: messageFn,
    promise,
    showToast,
  }
}
